packages:
  - "packages/*"
engineStrict: true
overrides:
  acorn: 8.17.0
  minimatch: 10.2.5
  postcss: 8.5.15
  tinyrainbow: 3.1.0
verifyDepsBeforeRun: error
onlyBuiltDependencies:
  - "@bufbuild/buf"
allowBuilds:
  "@bufbuild/buf": true
